# Generated by Django 2.2 on 2019-04-25 15:59

import apps.membership.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20190421_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.membership.models.event_image_file_path_func),
        ),
        migrations.AddField(
            model_name='event',
            name='map_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='map_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
