# Generated by Django 2.2 on 2019-04-29 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20190429_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer', to=settings.AUTH_USER_MODEL),
        ),
    ]
