# Generated by Django 2.1.7 on 2019-03-29 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='licenses',
            field=models.ManyToManyField(blank=True, through='membership.RacerLicense', to='membership.License'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='race_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer', to='membership.RaceCategory'),
        ),
    ]
