# Generated by Django 2.2 on 2019-04-21 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20190329_0756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='StaffPromotor',
        ),
        migrations.AlterField(
            model_name='staffpromotor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_promotor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='racer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer', to=settings.AUTH_USER_MODEL),
        ),
    ]
