# Generated by Django 2.2 on 2019-04-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# noinspection PyPep8Naming
def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Racer = apps.get_model("membership", "Racer")
    for o in Racer.objects.using(db_alias).filter(user__isnull=False).all():
        o.first_name = o.user.first_name
        o.last_name = o.user.last_name
        o.save()


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20190429_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='first_name',
            field=models.CharField(default='F1', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racer',
            name='last_name',
            field=models.CharField(default='L1', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racer',
            name='uid',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='Racer ID'),
        ),
        migrations.AlterField(
            model_name='staffpromotor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='staff_promotor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
