# Generated by Django 2.2 on 2019-06-29 09:17

from django.db import migrations


def forwards_func(apps, schema_editor):
    from race_membership.helpers.utils import capitalize_name

    db_alias = schema_editor.connection.alias
    Racer = apps.get_model("membership", "Racer")
    for o in Racer.objects.using(db_alias).all():
        o.first_name = capitalize_name(o.first_name)
        o.last_name = capitalize_name(o.last_name)
        o.save(update_fields=['first_name', 'last_name'])


# noinspection PyUnusedLocal
def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20190429_1450'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
